# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_service_pb2 as grpc__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class gRPCServiceStub(object):
    """gRPC service definition

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableMotions = channel.unary_unary(
                '/grpc_comm.gRPCService/GetAvailableMotions',
                request_serializer=grpc__service__pb2.GetMotionsRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetMotionsResponse.FromString,
                _registered_method=True)
        self.ExecuteSequence = channel.unary_unary(
                '/grpc_comm.gRPCService/ExecuteSequence',
                request_serializer=grpc__service__pb2.ExecuteSequenceRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.ExecuteSequenceResponse.FromString,
                _registered_method=True)
        self.GetSensorList = channel.unary_unary(
                '/grpc_comm.gRPCService/GetSensorList',
                request_serializer=grpc__service__pb2.GetSensorListRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetSensorListResponse.FromString,
                _registered_method=True)
        self.GetLidarData = channel.unary_unary(
                '/grpc_comm.gRPCService/GetLidarData',
                request_serializer=grpc__service__pb2.GetLidarDataRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetLidarDataResponse.FromString,
                _registered_method=True)
        self.StreamLidarData = channel.unary_stream(
                '/grpc_comm.gRPCService/StreamLidarData',
                request_serializer=grpc__service__pb2.GetLidarDataRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetLidarDataResponse.FromString,
                _registered_method=True)
        self.GetCameraData = channel.unary_unary(
                '/grpc_comm.gRPCService/GetCameraData',
                request_serializer=grpc__service__pb2.GetCameraDataRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetCameraDataResponse.FromString,
                _registered_method=True)
        self.StreamCameraData = channel.unary_stream(
                '/grpc_comm.gRPCService/StreamCameraData',
                request_serializer=grpc__service__pb2.GetCameraDataRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetCameraDataResponse.FromString,
                _registered_method=True)
        self.GetDepthData = channel.unary_unary(
                '/grpc_comm.gRPCService/GetDepthData',
                request_serializer=grpc__service__pb2.GetDepthDataRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetDepthDataResponse.FromString,
                _registered_method=True)
        self.GetRobotState = channel.unary_unary(
                '/grpc_comm.gRPCService/GetRobotState',
                request_serializer=grpc__service__pb2.GetRobotStateRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.GetRobotStateResponse.FromString,
                _registered_method=True)


class gRPCServiceServicer(object):
    """gRPC service definition

    """

    def GetAvailableMotions(self, request, context):
        """Motion control interface
        Get available motion module list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSequence(self, request, context):
        """Execute motion sequence
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorList(self, request, context):
        """Sensor information interface
        Get available sensor list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLidarData(self, request, context):
        """Lidar data interface
        Get lidar point cloud data (single shot)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLidarData(self, request, context):
        """Lidar data stream (server side stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameraData(self, request, context):
        """Camera data interface
        Get camera image (single shot)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCameraData(self, request, context):
        """Camera data stream (server side stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepthData(self, request, context):
        """Get depth data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """Get robot state data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableMotions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableMotions,
                    request_deserializer=grpc__service__pb2.GetMotionsRequest.FromString,
                    response_serializer=grpc__service__pb2.GetMotionsResponse.SerializeToString,
            ),
            'ExecuteSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSequence,
                    request_deserializer=grpc__service__pb2.ExecuteSequenceRequest.FromString,
                    response_serializer=grpc__service__pb2.ExecuteSequenceResponse.SerializeToString,
            ),
            'GetSensorList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorList,
                    request_deserializer=grpc__service__pb2.GetSensorListRequest.FromString,
                    response_serializer=grpc__service__pb2.GetSensorListResponse.SerializeToString,
            ),
            'GetLidarData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLidarData,
                    request_deserializer=grpc__service__pb2.GetLidarDataRequest.FromString,
                    response_serializer=grpc__service__pb2.GetLidarDataResponse.SerializeToString,
            ),
            'StreamLidarData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLidarData,
                    request_deserializer=grpc__service__pb2.GetLidarDataRequest.FromString,
                    response_serializer=grpc__service__pb2.GetLidarDataResponse.SerializeToString,
            ),
            'GetCameraData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameraData,
                    request_deserializer=grpc__service__pb2.GetCameraDataRequest.FromString,
                    response_serializer=grpc__service__pb2.GetCameraDataResponse.SerializeToString,
            ),
            'StreamCameraData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCameraData,
                    request_deserializer=grpc__service__pb2.GetCameraDataRequest.FromString,
                    response_serializer=grpc__service__pb2.GetCameraDataResponse.SerializeToString,
            ),
            'GetDepthData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepthData,
                    request_deserializer=grpc__service__pb2.GetDepthDataRequest.FromString,
                    response_serializer=grpc__service__pb2.GetDepthDataResponse.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=grpc__service__pb2.GetRobotStateRequest.FromString,
                    response_serializer=grpc__service__pb2.GetRobotStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_comm.gRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_comm.gRPCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class gRPCService(object):
    """gRPC service definition

    """

    @staticmethod
    def GetAvailableMotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/GetAvailableMotions',
            grpc__service__pb2.GetMotionsRequest.SerializeToString,
            grpc__service__pb2.GetMotionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/ExecuteSequence',
            grpc__service__pb2.ExecuteSequenceRequest.SerializeToString,
            grpc__service__pb2.ExecuteSequenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensorList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/GetSensorList',
            grpc__service__pb2.GetSensorListRequest.SerializeToString,
            grpc__service__pb2.GetSensorListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLidarData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/GetLidarData',
            grpc__service__pb2.GetLidarDataRequest.SerializeToString,
            grpc__service__pb2.GetLidarDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLidarData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_comm.gRPCService/StreamLidarData',
            grpc__service__pb2.GetLidarDataRequest.SerializeToString,
            grpc__service__pb2.GetLidarDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameraData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/GetCameraData',
            grpc__service__pb2.GetCameraDataRequest.SerializeToString,
            grpc__service__pb2.GetCameraDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCameraData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_comm.gRPCService/StreamCameraData',
            grpc__service__pb2.GetCameraDataRequest.SerializeToString,
            grpc__service__pb2.GetCameraDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepthData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/GetDepthData',
            grpc__service__pb2.GetDepthDataRequest.SerializeToString,
            grpc__service__pb2.GetDepthDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_comm.gRPCService/GetRobotState',
            grpc__service__pb2.GetRobotStateRequest.SerializeToString,
            grpc__service__pb2.GetRobotStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
